language: dart
dart:
# Install the latest stable release
- stable

dart_task:

# As long as you don't want any other configuration, you can just use the name
# of a task instead of "name: true".
- test
- dartanalyzer: --fatal-warnings --fatal-infos lib
- dartfmt

before_install:
  - docker run -d -p 127.0.0.1:3306:3306 mysql:5 -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -e MYSQL_ROOT_PASSWORD=$TEST_PASSWORD
  - docker run jwilder/dockerize:0.6.1 dockerize -timeout=160s -wait=tcp://127.0.0.1:3306

env:
  jobs:
    - TEST_PASSWORD: ""
    - TEST_PASSWORD: "secure"

services:
- docker