language: dart
dart:
# Install the latest stable release
- stable

dart_task:

# As long as you don't want any other configuration, you can just use the name
# of a task instead of "name: true".
- test
- dartanalyzer: --fatal-warnings --fatal-infos lib
- dartfmt

before_install:
  - docker pull carlad/sinatra
  - docker run -d -p 127.0.0.1:3006:3306 mysql:5
  - docker ps -a

env:
  jobs:
    - TEST_PASSWORD: ""
    - TEST_PASSWORD: "secure"

services:
- docker